database:
  user: hanko
  password: hanko
  host: localhost
  port: 5432
  dialect: postgres
smtp:
    host: smtp.example.com
    user: example
    password: example
server:
  public:
    cors:
      allow_origins:
        - http://localhost:63342
        - http://localhost:8000/
passcode:
  email:
    from_address: no-reply@hanko.io
secrets:
  keys:
    - abcedfghijklmnopqrstuvwxyz
service:
  name: Hanko Authentication Service
webauthn:
  relying_party:
    id: localhost
    origins:
      - http://localhost:63342
      - http://localhost:8000
password:
  enabled: false
emails:
  require_verification: true
passkey:
  onboarding:
    enabled: true
identifier:
  username:
    enabled: true
    optional: true
    max_length: 255
    min_length: 3
    allowed_characters: "abcdefghijklmnopqrstuvwxyz123456789-_."
  email:
    enabled: true
    optional: false
    verification: true # maybe we should also consider separate opitional attribute or is false interpreted as optional and true as required (and disabled does not exist)
