database:
  user: hanko
  password: hanko
  host: localhost
  port: 5432
  dialect: postgres
smtp:
    host: smtp.example.com
    user: example
    password: example
server:
  public:
    cors:
      allow_origins:
        - http://localhost:63342
        - http://localhost:8000/
passcode:
  email:
    from_address: no-reply@hanko.io
secrets:
  keys:
    - abcedfghijklmnopqrstuvwxyz
service:
  name: Hanko Authentication Service
webauthn:
  relying_party:
    id: localhost
    origins:
      - http://localhost:63342
      - http://localhost:8000
password:
  enabled: false
  optional: true
  acquire_on_registration: conditional
  acquire_on_login: always
  recovery: true
emails:
  require_verification: true
passkey:
  enabled: true
  optional: true
  acquire_on_registration: always
  acquire_on_login: always
  attestation_preference: direct
  limit: 100
  onboarding:
    enabled: true
email:
  enabled: true
  optional: true
  acquire_on_registration: true
  acquire_on_login: false
  require_verification: true
  limit: 100
  use_as_login_identifier: true
  max_length: 100
  use_for_authentication: false
  passcode_ttl: 300
username:
  enabled: true
  optional: true
  acquire_on_registration: true
  acquire_on_login: false
  use_as_login_identifier: true
  max_length: 100
rate_limiter:
  enabled: false
email_delivery:
  from_address: no-reply@hanko.io
  smtp:
    host: localhost
    port: 2500
