database:
  user: hanko
  password: hanko
  host: postgresd
  port: 5432
  dialect: postgres
smtp:
  host: "mailslurper"
  port: "2500"
passcode:
  email:
    from_address: no-reply@hanko.io
secrets:
  keys:
    - abcedfghijklmnopqrstuvwxyz
service:
  name: Hanko Authentication Service
webauthn:
  relying_party:
    origins:
      - "http://localhost:8888"
session:
  cookie:
    secure: false # is needed for safari, because safari does not store secure cookies on localhost
server:
  public:
    cors:
      allow_origins:
        - "http://localhost:8888"
third_party:
  allowed_redirect_urls:
    - http://localhost:8888**
  redirect_url: http://localhost:8000/thirdparty/callback
  error_redirect_url: http://localhost:8888
  providers:
    linkedin:
      client_id: 784q78dncvrauv
      secret: WPL_AP0.5r1Ldz9Ie497zCKy.NjM2NjE1NjU5
      enabled: true
      allow_linking: true
    github:
      client_id: 784q78dncvrauv
      secret: WPL_AP0.5r1Ldz9Ie497zCKy.NjM2NjE1NjU5
      enabled: true
      allow_linking: true
